name: Python App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest  # Використовуємо Windows для створення .exe файлу

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --hidden-import PyQt5 --hidden-import numpy --add-data "methods;methods" main.py


      - name: Create release tag
        id: tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Створюємо тег з датою
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload executable to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}  # Використовуємо тег для релізу
          files: dist/solver.exe  # Завантажуємо зібраний .exe файл
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
